// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var HostmetricsProcessBootTimeCacheFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"hostmetrics.process.bootTimeCache",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, all process scrapes will use the boot time value that is cached at the start of the process."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28849"),
	featuregate.WithRegisterFromVersion("v0.98.0"),
)

var ReceiverHostmetricsreceiverHostIdentityFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.hostmetricsreceiver.HostIdentity",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the receiver detects the host's identity and attaches host.id, host.name and service.instance.id to the resources it emits, so host metrics carry identity without the resourcedetection processor."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/46207"),
	featuregate.WithRegisterFromVersion("v0.159.0"),
)

var ReceiverHostmetricsreceiverUseLinuxMemAvailableFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.hostmetricsreceiver.UseLinuxMemAvailable",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, the used value for the system.memory.usage and system.memory.utilization metrics will be based on the Linux kernel's MemAvailable statistic instead of MemFree, Buffers, and Cached."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42221"),
	featuregate.WithRegisterFromVersion("v0.137.0"),
)
